# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/som/Documents/code/cppsp1explorations/silk_st_sp1/silkworm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/som/Documents/code/cppsp1explorations/silk_st_sp1/silkworm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/som/Documents/code/cppsp1explorations/silk_st_sp1/silkworm/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/som/Documents/code/cppsp1explorations/silk_st_sp1/silkworm/CMakeFiles /home/som/Documents/code/cppsp1explorations/silk_st_sp1/silkworm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/som/Documents/code/cppsp1explorations/silk_st_sp1/silkworm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/som/Documents/code/cppsp1explorations/silk_st_sp1/silkworm/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named silkworm-buildinfo-git

# Build rule for target.
silkworm-buildinfo-git: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 silkworm-buildinfo-git
.PHONY : silkworm-buildinfo-git

# fast build rule for target.
silkworm-buildinfo-git/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silkworm-buildinfo-git.dir/build.make CMakeFiles/silkworm-buildinfo-git.dir/build
.PHONY : silkworm-buildinfo-git/fast

#=============================================================================
# Target rules for targets named silkworm-buildinfo

# Build rule for target.
silkworm-buildinfo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 silkworm-buildinfo
.PHONY : silkworm-buildinfo

# fast build rule for target.
silkworm-buildinfo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silkworm-buildinfo.dir/build.make CMakeFiles/silkworm-buildinfo.dir/build
.PHONY : silkworm-buildinfo/fast

#=============================================================================
# Target rules for targets named all_unit_tests

# Build rule for target.
all_unit_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_unit_tests
.PHONY : all_unit_tests

# fast build rule for target.
all_unit_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_unit_tests.dir/build.make CMakeFiles/all_unit_tests.dir/build
.PHONY : all_unit_tests/fast

#=============================================================================
# Target rules for targets named blst

# Build rule for target.
blst: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blst
.PHONY : blst

# fast build rule for target.
blst/fast:
	$(MAKE) $(MAKESILENT) -f third_party/blst/CMakeFiles/blst.dir/build.make third_party/blst/CMakeFiles/blst.dir/build
.PHONY : blst/fast

#=============================================================================
# Target rules for targets named keccak

# Build rule for target.
keccak: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 keccak
.PHONY : keccak

# fast build rule for target.
keccak/fast:
	$(MAKE) $(MAKESILENT) -f third_party/ethash/ethash/lib/keccak/CMakeFiles/keccak.dir/build.make third_party/ethash/ethash/lib/keccak/CMakeFiles/keccak.dir/build
.PHONY : keccak/fast

#=============================================================================
# Target rules for targets named ethash

# Build rule for target.
ethash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ethash
.PHONY : ethash

# fast build rule for target.
ethash/fast:
	$(MAKE) $(MAKESILENT) -f third_party/ethash/ethash/lib/ethash/CMakeFiles/ethash.dir/build.make third_party/ethash/ethash/lib/ethash/CMakeFiles/ethash.dir/build
.PHONY : ethash/fast

#=============================================================================
# Target rules for targets named gmplib

# Build rule for target.
gmplib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmplib
.PHONY : gmplib

# fast build rule for target.
gmplib/fast:
	$(MAKE) $(MAKESILENT) -f third_party/gmp/CMakeFiles/gmplib.dir/build.make third_party/gmp/CMakeFiles/gmplib.dir/build
.PHONY : gmplib/fast

#=============================================================================
# Target rules for targets named ff

# Build rule for target.
ff: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ff
.PHONY : ff

# fast build rule for target.
ff/fast:
	$(MAKE) $(MAKESILENT) -f third_party/libff/libff/libff/CMakeFiles/ff.dir/build.make third_party/libff/libff/libff/CMakeFiles/ff.dir/build
.PHONY : ff/fast

#=============================================================================
# Target rules for targets named secp256k1

# Build rule for target.
secp256k1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 secp256k1
.PHONY : secp256k1

# fast build rule for target.
secp256k1/fast:
	$(MAKE) $(MAKESILENT) -f third_party/secp256k1/CMakeFiles/secp256k1.dir/build.make third_party/secp256k1/CMakeFiles/secp256k1.dir/build
.PHONY : secp256k1/fast

#=============================================================================
# Target rules for targets named evmone

# Build rule for target.
evmone: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 evmone
.PHONY : evmone

# fast build rule for target.
evmone/fast:
	$(MAKE) $(MAKESILENT) -f third_party/evmone/CMakeFiles/evmone.dir/build.make third_party/evmone/CMakeFiles/evmone.dir/build
.PHONY : evmone/fast

#=============================================================================
# Target rules for targets named instructions

# Build rule for target.
instructions: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 instructions
.PHONY : instructions

# fast build rule for target.
instructions/fast:
	$(MAKE) $(MAKESILENT) -f third_party/evmone/evmone/evmc/lib/instructions/CMakeFiles/instructions.dir/build.make third_party/evmone/evmone/evmc/lib/instructions/CMakeFiles/instructions.dir/build
.PHONY : instructions/fast

#=============================================================================
# Target rules for targets named loader

# Build rule for target.
loader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 loader
.PHONY : loader

# fast build rule for target.
loader/fast:
	$(MAKE) $(MAKESILENT) -f third_party/evmone/evmone/evmc/lib/loader/CMakeFiles/loader.dir/build.make third_party/evmone/evmone/evmc/lib/loader/CMakeFiles/loader.dir/build
.PHONY : loader/fast

#=============================================================================
# Target rules for targets named tooling

# Build rule for target.
tooling: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tooling
.PHONY : tooling

# fast build rule for target.
tooling/fast:
	$(MAKE) $(MAKESILENT) -f third_party/evmone/evmone/evmc/lib/tooling/CMakeFiles/tooling.dir/build.make third_party/evmone/evmone/evmc/lib/tooling/CMakeFiles/tooling.dir/build
.PHONY : tooling/fast

#=============================================================================
# Target rules for targets named silkworm_core

# Build rule for target.
silkworm_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 silkworm_core
.PHONY : silkworm_core

# fast build rule for target.
silkworm_core/fast:
	$(MAKE) $(MAKESILENT) -f silkworm/core/CMakeFiles/silkworm_core.dir/build.make silkworm/core/CMakeFiles/silkworm_core.dir/build
.PHONY : silkworm_core/fast

#=============================================================================
# Target rules for targets named silkworm_dev

# Build rule for target.
silkworm_dev: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 silkworm_dev
.PHONY : silkworm_dev

# fast build rule for target.
silkworm_dev/fast:
	$(MAKE) $(MAKESILENT) -f silkworm/dev/CMakeFiles/silkworm_dev.dir/build.make silkworm/dev/CMakeFiles/silkworm_dev.dir/build
.PHONY : silkworm_dev/fast

silkworm/buildinfo.o: silkworm/buildinfo.c.o
.PHONY : silkworm/buildinfo.o

# target to build an object file
silkworm/buildinfo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silkworm-buildinfo.dir/build.make CMakeFiles/silkworm-buildinfo.dir/silkworm/buildinfo.c.o
.PHONY : silkworm/buildinfo.c.o

silkworm/buildinfo.i: silkworm/buildinfo.c.i
.PHONY : silkworm/buildinfo.i

# target to preprocess a source file
silkworm/buildinfo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silkworm-buildinfo.dir/build.make CMakeFiles/silkworm-buildinfo.dir/silkworm/buildinfo.c.i
.PHONY : silkworm/buildinfo.c.i

silkworm/buildinfo.s: silkworm/buildinfo.c.s
.PHONY : silkworm/buildinfo.s

# target to generate assembly for a file
silkworm/buildinfo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silkworm-buildinfo.dir/build.make CMakeFiles/silkworm-buildinfo.dir/silkworm/buildinfo.c.s
.PHONY : silkworm/buildinfo.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... all_unit_tests"
	@echo "... blst"
	@echo "... gmplib"
	@echo "... silkworm-buildinfo-git"
	@echo "... ethash"
	@echo "... evmone"
	@echo "... ff"
	@echo "... instructions"
	@echo "... keccak"
	@echo "... loader"
	@echo "... secp256k1"
	@echo "... silkworm-buildinfo"
	@echo "... silkworm_core"
	@echo "... silkworm_dev"
	@echo "... tooling"
	@echo "... silkworm/buildinfo.o"
	@echo "... silkworm/buildinfo.i"
	@echo "... silkworm/buildinfo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/som/Documents/code/cppsp1explorations/silk_st_sp1/silkworm/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

