# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/som/Documents/code/cppsp1explorations/silk_st_sp1/silkworm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/som/Documents/code/cppsp1explorations/silk_st_sp1/silkworm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@echo "Running external command ..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@echo "Running external command ..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/som/Documents/code/cppsp1explorations/silk_st_sp1/silkworm/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@echo "Running external command ..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@echo "Running external command ..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@echo "Running external command ..."
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@echo "Running external command ..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@echo "Running external command ..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@echo "Running external command ..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@echo "Running external command ..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@echo "Running external command ..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@echo "Running external command ..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/som/Documents/code/cppsp1explorations/silk_st_sp1/silkworm/CMakeFiles /home/som/Documents/code/cppsp1explorations/silk_st_sp1/silkworm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/som/Documents/code/cppsp1explorations/silk_st_sp1/silkworm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named silkworm-buildinfo-git

# Build rule for target.
silkworm-buildinfo-git: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 silkworm-buildinfo-git
.PHONY : silkworm-buildinfo-git

# fast build rule for target.
silkworm-buildinfo-git/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silkworm-buildinfo-git.dir/build.make CMakeFiles/silkworm-buildinfo-git.dir/build
.PHONY : silkworm-buildinfo-git/fast

#=============================================================================
# Target rules for targets named silkworm-buildinfo

# Build rule for target.
silkworm-buildinfo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 silkworm-buildinfo
.PHONY : silkworm-buildinfo

# fast build rule for target.
silkworm-buildinfo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silkworm-buildinfo.dir/build.make CMakeFiles/silkworm-buildinfo.dir/build
.PHONY : silkworm-buildinfo/fast

#=============================================================================
# Target rules for targets named blst

# Build rule for target.
blst: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blst
.PHONY : blst

# fast build rule for target.
blst/fast:
	$(MAKE) $(MAKESILENT) -f third_party/blst/CMakeFiles/blst.dir/build.make third_party/blst/CMakeFiles/blst.dir/build
.PHONY : blst/fast

#=============================================================================
# Target rules for targets named keccak

# Build rule for target.
keccak: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 keccak
.PHONY : keccak

# fast build rule for target.
keccak/fast:
	$(MAKE) $(MAKESILENT) -f third_party/ethash/ethash/lib/keccak/CMakeFiles/keccak.dir/build.make third_party/ethash/ethash/lib/keccak/CMakeFiles/keccak.dir/build
.PHONY : keccak/fast

#=============================================================================
# Target rules for targets named ethash

# Build rule for target.
ethash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ethash
.PHONY : ethash

# fast build rule for target.
ethash/fast:
	$(MAKE) $(MAKESILENT) -f third_party/ethash/ethash/lib/ethash/CMakeFiles/ethash.dir/build.make third_party/ethash/ethash/lib/ethash/CMakeFiles/ethash.dir/build
.PHONY : ethash/fast

#=============================================================================
# Target rules for targets named ff

# Build rule for target.
ff: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ff
.PHONY : ff

# fast build rule for target.
ff/fast:
	$(MAKE) $(MAKESILENT) -f third_party/libff/libff/libff/CMakeFiles/ff.dir/build.make third_party/libff/libff/libff/CMakeFiles/ff.dir/build
.PHONY : ff/fast

#=============================================================================
# Target rules for targets named secp256k1

# Build rule for target.
secp256k1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 secp256k1
.PHONY : secp256k1

# fast build rule for target.
secp256k1/fast:
	$(MAKE) $(MAKESILENT) -f third_party/secp256k1/CMakeFiles/secp256k1.dir/build.make third_party/secp256k1/CMakeFiles/secp256k1.dir/build
.PHONY : secp256k1/fast

#=============================================================================
# Target rules for targets named evmone

# Build rule for target.
evmone: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 evmone
.PHONY : evmone

# fast build rule for target.
evmone/fast:
	$(MAKE) $(MAKESILENT) -f third_party/evmone/CMakeFiles/evmone.dir/build.make third_party/evmone/CMakeFiles/evmone.dir/build
.PHONY : evmone/fast

#=============================================================================
# Target rules for targets named instructions

# Build rule for target.
instructions: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 instructions
.PHONY : instructions

# fast build rule for target.
instructions/fast:
	$(MAKE) $(MAKESILENT) -f third_party/evmone/evmone/evmc/lib/instructions/CMakeFiles/instructions.dir/build.make third_party/evmone/evmone/evmc/lib/instructions/CMakeFiles/instructions.dir/build
.PHONY : instructions/fast

#=============================================================================
# Target rules for targets named loader

# Build rule for target.
loader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 loader
.PHONY : loader

# fast build rule for target.
loader/fast:
	$(MAKE) $(MAKESILENT) -f third_party/evmone/evmone/evmc/lib/loader/CMakeFiles/loader.dir/build.make third_party/evmone/evmone/evmc/lib/loader/CMakeFiles/loader.dir/build
.PHONY : loader/fast

#=============================================================================
# Target rules for targets named tooling

# Build rule for target.
tooling: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tooling
.PHONY : tooling

# fast build rule for target.
tooling/fast:
	$(MAKE) $(MAKESILENT) -f third_party/evmone/evmone/evmc/lib/tooling/CMakeFiles/tooling.dir/build.make third_party/evmone/evmone/evmc/lib/tooling/CMakeFiles/tooling.dir/build
.PHONY : tooling/fast

#=============================================================================
# Target rules for targets named cborcpp

# Build rule for target.
cborcpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cborcpp
.PHONY : cborcpp

# fast build rule for target.
cborcpp/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cbor-cpp/cbor-cpp/CMakeFiles/cborcpp.dir/build.make third_party/cbor-cpp/cbor-cpp/CMakeFiles/cborcpp.dir/build
.PHONY : cborcpp/fast

#=============================================================================
# Target rules for targets named cpp_base64

# Build rule for target.
cpp_base64: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpp_base64
.PHONY : cpp_base64

# fast build rule for target.
cpp_base64/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cpp-base64/CMakeFiles/cpp_base64.dir/build.make third_party/cpp-base64/CMakeFiles/cpp_base64.dir/build
.PHONY : cpp_base64/fast

#=============================================================================
# Target rules for targets named mdbx-static

# Build rule for target.
mdbx-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mdbx-static
.PHONY : mdbx-static

# fast build rule for target.
mdbx-static/fast:
	$(MAKE) $(MAKESILENT) -f third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx-static.dir/build.make third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx-static.dir/build
.PHONY : mdbx-static/fast

#=============================================================================
# Target rules for targets named mdbx_chk

# Build rule for target.
mdbx_chk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mdbx_chk
.PHONY : mdbx_chk

# fast build rule for target.
mdbx_chk/fast:
	$(MAKE) $(MAKESILENT) -f third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_chk.dir/build.make third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_chk.dir/build
.PHONY : mdbx_chk/fast

# Manual pre-install relink rule for target.
mdbx_chk/preinstall:
	$(MAKE) $(MAKESILENT) -f third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_chk.dir/build.make third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_chk.dir/preinstall
.PHONY : mdbx_chk/preinstall

#=============================================================================
# Target rules for targets named mdbx_copy

# Build rule for target.
mdbx_copy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mdbx_copy
.PHONY : mdbx_copy

# fast build rule for target.
mdbx_copy/fast:
	$(MAKE) $(MAKESILENT) -f third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_copy.dir/build.make third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_copy.dir/build
.PHONY : mdbx_copy/fast

# Manual pre-install relink rule for target.
mdbx_copy/preinstall:
	$(MAKE) $(MAKESILENT) -f third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_copy.dir/build.make third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_copy.dir/preinstall
.PHONY : mdbx_copy/preinstall

#=============================================================================
# Target rules for targets named mdbx_stat

# Build rule for target.
mdbx_stat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mdbx_stat
.PHONY : mdbx_stat

# fast build rule for target.
mdbx_stat/fast:
	$(MAKE) $(MAKESILENT) -f third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_stat.dir/build.make third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_stat.dir/build
.PHONY : mdbx_stat/fast

# Manual pre-install relink rule for target.
mdbx_stat/preinstall:
	$(MAKE) $(MAKESILENT) -f third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_stat.dir/build.make third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_stat.dir/preinstall
.PHONY : mdbx_stat/preinstall

#=============================================================================
# Target rules for targets named mdbx_dump

# Build rule for target.
mdbx_dump: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mdbx_dump
.PHONY : mdbx_dump

# fast build rule for target.
mdbx_dump/fast:
	$(MAKE) $(MAKESILENT) -f third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_dump.dir/build.make third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_dump.dir/build
.PHONY : mdbx_dump/fast

# Manual pre-install relink rule for target.
mdbx_dump/preinstall:
	$(MAKE) $(MAKESILENT) -f third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_dump.dir/build.make third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_dump.dir/preinstall
.PHONY : mdbx_dump/preinstall

#=============================================================================
# Target rules for targets named mdbx_load

# Build rule for target.
mdbx_load: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mdbx_load
.PHONY : mdbx_load

# fast build rule for target.
mdbx_load/fast:
	$(MAKE) $(MAKESILENT) -f third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_load.dir/build.make third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_load.dir/build
.PHONY : mdbx_load/fast

# Manual pre-install relink rule for target.
mdbx_load/preinstall:
	$(MAKE) $(MAKESILENT) -f third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_load.dir/build.make third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_load.dir/preinstall
.PHONY : mdbx_load/preinstall

#=============================================================================
# Target rules for targets named mdbx_drop

# Build rule for target.
mdbx_drop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mdbx_drop
.PHONY : mdbx_drop

# fast build rule for target.
mdbx_drop/fast:
	$(MAKE) $(MAKESILENT) -f third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_drop.dir/build.make third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_drop.dir/build
.PHONY : mdbx_drop/fast

# Manual pre-install relink rule for target.
mdbx_drop/preinstall:
	$(MAKE) $(MAKESILENT) -f third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_drop.dir/build.make third_party/erigon-mdbx-go/mdbx-go/mdbxdist/CMakeFiles/mdbx_drop.dir/preinstall
.PHONY : mdbx_drop/preinstall

silkworm/buildinfo.o: silkworm/buildinfo.c.o
.PHONY : silkworm/buildinfo.o

# target to build an object file
silkworm/buildinfo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silkworm-buildinfo.dir/build.make CMakeFiles/silkworm-buildinfo.dir/silkworm/buildinfo.c.o
.PHONY : silkworm/buildinfo.c.o

silkworm/buildinfo.i: silkworm/buildinfo.c.i
.PHONY : silkworm/buildinfo.i

# target to preprocess a source file
silkworm/buildinfo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silkworm-buildinfo.dir/build.make CMakeFiles/silkworm-buildinfo.dir/silkworm/buildinfo.c.i
.PHONY : silkworm/buildinfo.c.i

silkworm/buildinfo.s: silkworm/buildinfo.c.s
.PHONY : silkworm/buildinfo.s

# target to generate assembly for a file
silkworm/buildinfo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/silkworm-buildinfo.dir/build.make CMakeFiles/silkworm-buildinfo.dir/silkworm/buildinfo.c.s
.PHONY : silkworm/buildinfo.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... blst"
	@echo "... silkworm-buildinfo-git"
	@echo "... cborcpp"
	@echo "... cpp_base64"
	@echo "... ethash"
	@echo "... evmone"
	@echo "... ff"
	@echo "... instructions"
	@echo "... keccak"
	@echo "... loader"
	@echo "... mdbx-static"
	@echo "... mdbx_chk"
	@echo "... mdbx_copy"
	@echo "... mdbx_drop"
	@echo "... mdbx_dump"
	@echo "... mdbx_load"
	@echo "... mdbx_stat"
	@echo "... secp256k1"
	@echo "... silkworm-buildinfo"
	@echo "... tooling"
	@echo "... silkworm/buildinfo.o"
	@echo "... silkworm/buildinfo.i"
	@echo "... silkworm/buildinfo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

