/* Cable: CMake Bootstrap Library.
 * Copyright 2019 Pawel Bylica.
 * Licensed under the Apache License, Version 2.0.
 */

/* Generated by Cable Build Info on 2025-07-25T16:48:37. Do not modify directly. */

#pragma once

#define SILKWORM_VERSION "0.1.0-dev+commit.75fc66b9.dirty"

#ifdef __cplusplus
constexpr auto silkworm_version = "0.1.0-dev+commit.75fc66b9.dirty";
#endif
